### ISSUE TITLE
Do not use System.unique_integer in layer names

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#173]
The purpose behind using unique integer was to ensure that layers have unique names and parameters are mapped correctly to their corresponding layers. The issue is that it is a source of non-determinism in model creation. This makes it really difficult to correctly serialize and load models created from other sources. For example, if I want to serialize my trained model's parameters, they would get serialized as a container with parameters mapped to layer names with random integers. That means in order for somebody (or even myself) to use my model, I would need to re-build the model with exactly matching layer names.

Models created in exactly the same way should produce identical structs. The purpose of ordering with a unique integer was more relevant when parameters were tuples, but now it's not as big a deal. We really just need a way to count up as subsequent layers are added to the model.

**Comment by polvalente** [comment]
Perhaps the model itself could carry the number of layers it contains (which would also be the id of the next layer). If a global id is needed, we could just use `System.unique_integer()` to have a model id and then the global layer id would be model_id * 10 + layer_id or somthing like that
