### ISSUE TITLE
Avoid recompilations in user-defined transformations of loop state

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#180]
As one example `validate` forwards metrics to the outer loop state and thus after it runs the loop step needs to be recompiled. This is possible in other handlers as well if user's want to forward user-defined state for use later. This is something we should try to avoid if at all possible

**Comment by josevalim** [comment]
Why does it need to be recompiled? If the shape of the metrics is the same, there is no recompilation. Or do you mean something like this happens:

1. Metrics starts empty on first loop
2. Metrics are filled at the end of the first loop with new values
3. Metrics starts second loop with new values

If that's the case, recompilation happens twice... which we may want to avoid?

Some options for fixes are:

1. Initialize metrics to bogus values
2. Or separate the metrics internal state from their reported state

**Comment by seanmor5** [comment]
This has been mostly resolved, there will be recompilations in certain cases, but I added a note to the docs about those!
