### ISSUE TITLE
Remove input shape rank restriction

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#184]
To fully support ONNX, we will need to allow scalar shapes, rank 1 shapes, etc. The shape check takes place inside `Axon.Shape.input`; however, there are several places where we use the rank assumption to do shape calculations - e.g. we use `elem(shape, 0)` without actually checking if the shape is not a scalar. We need to go through and change all of these cases.

**Comment by floatn** [comment]
In particular case of `elem(shape,` wouldn't it be a good idea to create like a `Shape.elem` function to replace raw `elem` calls, where it'll be possible to handle different (i.e. scalar) types of shapes?
