### ISSUE TITLE
Early stopping handle_meta is nil

### ISSUE THREAD

**Issue by philipbrown** [elixir-nx/axon#215]
Hey!

I've just tried adding early stopping, but it errored because `handle_meta` was nil (during the `Map.replace/3`):
https://github.com/elixir-nx/axon/blob/c51bd3ef95076c6b0e6a334a3d7f07f4cc70239c/lib/axon/loop.ex#L1041-L1044

I've had a quick look through, and I'm not sure if it ever get's initialised as a map?

**Comment by seanmor5** [comment]
@philipbrown Good catch! Can you try again on main?

**Comment by philipbrown** [comment]
@seanmor5 Sorry, it took me ages to test this! Yep, it's working now 👍
