### ISSUE TITLE
Move model_state inside JIT in training loop

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#244]

**Comment by noozo** [comment]
Is axon unusable atm? The credit_card_fraud example doesn't work because of this (at least using EXLA). 

Is there a way to work around it while this issue persists?

**Comment by josevalim** [comment]
Axon has not been fully updated to Nx+EXLA v0.2 yet, which is why you may run into bugs. If you rollback to previous EXLA versions on Git (the ones before EXLA.Backend were introduced), then it should work.

**Comment by noozo** [comment]
Guess i'll wait then. Might as well have my new code with EXLA 0.2 already. Thanks!

**Comment by alisinabh** [comment]
Now I'm getting this error in the evaluator Loop in `recur_predict_fun`. I cannot get any Loop evaluator to work with EXLA.

```
** (RuntimeError) cannot invoke Nx function because it relies on two incompatible tensor implementations: 
Nx.Defn.Expr and EXLA.Backend. You may need to call Nx.backend_transfer/1 (or Nx.backend_copy/1) 
on one or both of them to transfer them to a common implementation
    (nx 0.3.0-dev) lib/nx/shared.ex:447: Nx.Shared.pick_struct/2
    (nx 0.3.0-dev) lib/nx.ex:3238: Nx.element_wise_bin_op/4
    (axon 0.1.0-dev) lib/axon/compiler.ex:379: anonymous fn/15 in Axon.Compiler.recur_predict_fun/3
    (axon 0.1.0-dev) lib/axon/compiler.ex:192: Axon.Compiler.call_predict_cache/6
    (axon 0.1.0-dev) lib/axon/compiler.ex:336: anonymous fn/8 in Axon.Compiler.recur_predict_fun/3
    (elixir 1.13.4) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (axon 0.1.0-dev) lib/axon/compiler.ex:334: anonymous fn/15 in Axon.Compiler.recur_predict_fun/3
    (axon 0.1.0-dev) lib/axon/compiler.ex:192: Axon.Compiler.call_predict_cache/6
```

**Comment by josevalim** [comment]
@alisinabh can you provide a way to reproduce the issue? :)

**Comment by josevalim** [comment]
Also please make sure to use latest Axon too!

**Comment by alisinabh** [comment]
@josevalim You can try `examples/vision/cifar10.exs` example. The the evaluation loop is not working because of this error.
Also the accuracy metric seems wrong to me but I'm not sure.

I'm also using the latest Axon from the main branch.

**Comment by alisinabh** [comment]
In the last commit (06a5526266dbfa7165168433e58633809fc04bf6) there is a backend_transfer call added to one of `recur_predict_fun`.
Maybe we need to add this call to all of them?
