### ISSUE TITLE
Make RNN outputs configurable

### ISSUE THREAD

**Issue by alisinabh** [elixir-nx/axon#252]
Give a model using a RNN layer, we need to be able to configure the shape/slice of the output layer.

For example let's say in the following snippet we want the very last slice of the LSTM sequence. Currently the workaround that @seanmor5 suggested was to define custom slice functions so we can manipulate the output shape.

```elixir
model =
  Axon.input({nil, sequence_length, 1})
  |> Axon.lstm(256)
  |> then(fn {{cell, hidden}, out} -> out end)
  |> Axon.nx(fn x -> Nx.slice_along_axis(x, sequence_length - 1, 1, axis: -2) end)
  |> Axon.flatten()
  |> Axon.dropout(rate: 0.2)
  |> Axon.dense(vocab_count, activation: :softmax)
```

**Comment by seanmor5** [comment]
@alisinabh I have been doing some thinking and I think it's best to keep the return type the same always. That way the user always knows what to expect from the API. It's easy enough to handle with `nx` and/or custom layers!

**Comment by alisinabh** [comment]
Good. Then I think it would help if we mention this in the documentation of RNN layers.

**Comment by seanmor5** [comment]
@alisinabh I agree! Please feel free to open a PR :)
