### ISSUE TITLE
Add model import/export API

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#26]
Need ability to serialize models to/from external formats. Model serialization is serialization of the actual computation graph. We should also have the ability to save and load model parameters, but I believe part of that discussion needs to happen upstream with a common `Nx` tensor serialization format. See e.g. https://github.com/elixir-nx/nx/issues/354

**Comment by seanmor5** [comment]
I have thought a bit about this issue and have the following proposal.

First, the training API needs to be updated to accept either a model initialization function or already existing parameters or even a combination of both. This was brought up by @arpieb when doing some RL applications. This will definitely also be necessary for transfer learning where we import part of the model and initialize another part for training.

Second, I would introduce the following methods for now into the Axon API:

```elixir
load(file_or_url, opts \\ []) :: {:ok, {model, params}} | {:ok, model} | {:error, msg}

export(model, opts \\ []) :: :ok | {:error, msg}
export(model, params, opts \\ []) :: :ok | {:error, msg}
```

The reason for there not being any methods for loading/saving weights specifically is because I believe that is mostly related to https://github.com/elixir-nx/nx/issues/354 and a responsibility that should be on Nx. 

An example of working with this API would be something like:

```elixir
file = ...get file from somewhere (like tfhub)...

{model, params} = Axon.load(file, format: TFLite)

Axon.predict(model, params, inp)
```

In order to include part of a model in something like transfer learning, we'd need to indicate the layers are frozen. It's an Axon struct, so I would suggest something similar to:

```elixir
{feature_extractor, fe_params} = Axon.load(file, format: TFLite)

model =
  feature_extractor
  |> Axon.freeze(fe_params, filter: :all)
  |> Axon.flatten()
  |> Axon.dense(10, activation: :softmax)
```

**Comment by arpieb** [comment]
Might I suggest defining an import/export protocol to standardize the workflow for other possible formats?  Axon should definitely roll its own implementation for completeness, expediency, and tight integration with Nx.  That being said, a well-defined protocol would also allow external modules to im-/export Axon models into formats like ONNX, HDF5, XML (don't laugh too hard - you can encode binary data, and I've seen it in the wild!), etc ad nauseum - pretty much any format that can support graph architecture as well as stateful data (weights, biases, recurrent components).  Some day not far in the future someone will train a model in Axon leveraging distributed, streaming training and want to export it for production... ;)

Freezing layers and the ability to cherry-pick layers from an existing model as input or output for an Axon model is definitely going to be needed for transfer learning, but I'd argue that is another separate issue from import/export.  Glad to see it's on the roadmap though!
