### ISSUE TITLE
Strange output from CuDNN when running mobilenet_v3

### ISSUE THREAD

**Issue by jallum** [elixir-nx/axon#264]
```
23:09:49.582 [info]  XLA service 0x7fc7b04c69f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:

23:09:49.590 [info]    StreamExecutor device (0): NVIDIA TITAN V, Compute Capability 7.0

23:09:49.590 [info]  Using BFC allocator.

23:09:49.590 [info]  XLA backend will use up to 10551715430 bytes on device 0 for BFCAllocator.

23:09:49.740 [warning] unk__666 has no specified dimension, assuming nil

23:09:50.784 [info]  Loaded cuDNN version 8400

23:09:50.840 [error] Disabling cuDNN frontend for the following convolution:
  input: {count: 64 feature_map_count: 32 spatial: 112 112  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 32 input_feature_map_count: 1 layout: OutputInputYX shape: 3 3 }
  {zero_padding: 1 1  pad_alignment: default filter_strides: 1 1  dilation_rates: 1 1 }
  ... because the current cuDNN version does not support it.

23:09:51.845 [error] Disabling cuDNN frontend for the following convolution:
  input: {count: 64 feature_map_count: 32 spatial: 112 112  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
  filter: {output_feature_map_count: 16 input_feature_map_count: 32 layout: OutputInputYX shape: 1 1 }
  {zero_padding: 0 0  pad_alignment: default filter_strides: 1 1  dilation_rates: 1 1 }
  ... because the current cuDNN version does not support it.
.
.
.
```

**Comment by seanmor5** [comment]
@jallum This is likely a result of incompatible cuDNN versions embedded in our XLA builds. I'm not 100% sure what version of cuDNN we build XLA with, but I'm not sure they are 100% backwards compatible. An (annoying) option is to run with:

```elixir
$ export XLA_BUILD=true
$ export XLA_TARGET=cuda
$ mix run ...
```

Which will build the XLA binary from source. But if you don't want to go through the long build process, I will investigate expanding our XLA build matrix

**Comment by josevalim** [comment]
What is your cuda version @jallum?

We support only 11.1+ and it seems you are using latest CuDNN anyway: https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

**Comment by jallum** [comment]
11.4, on the 470.xx drivers.

i've been digging into this and _i think_ it's a symptom of a problem in the EXLA.Backend. using the observer, i took note of the ETS tables before and after I see this issue output, and i've noticed that it coincides with a _massive_ explosion of records in the `EXLA.Defn.LockedCache` table (somewhere on the order of ~65k records) and near complete exhaustion of memory on the GPU. looking deeper still, i noticed that the key that's being used in the LockedCache has an anonymous function component, like so: (more on that in a minute)

```{#Function<82.45485230/1 in EXLA.Backend.reshape/2>, [{{:f, 32}, {224, 224, 3}, [:width, :height, :channels]}]}```

...repeated over and over like so (added some logging):

```
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179335>} locking "{#Function<82.45485230/1 in EXLA.Backend.reshape/2>, [{{:f, 32}, {224, 224, 3}, [:width, :height, :channels]}]}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179342>} locking "{#Function<82.45485230/1 in EXLA.Backend.reshape/2>, [{{:f, 32}, {224, 224, 3}}], :cuda, [], []}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179376>} locking "{#Function<32.45485230/2 in EXLA.Backend.divide/3>, [{{:u, 8}, {224, 224, 3}, [:width, :height, :channels]}, {{:f, 32}, {}, []}]}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179384>} locking "{#Function<32.45485230/2 in EXLA.Backend.divide/3>, [{{:u, 8}, {224, 224, 3}}, {{:f, 32}, {}}], :cuda, [], []}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179412>} locking "{#Function<82.45485230/1 in EXLA.Backend.reshape/2>, [{{:f, 32}, {224, 224, 3}, [:width, :height, :channels]}]}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179419>} locking "{#Function<82.45485230/1 in EXLA.Backend.reshape/2>, [{{:f, 32}, {224, 224, 3}}], :cuda, [], []}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179453>} locking "{#Function<32.45485230/2 in EXLA.Backend.divide/3>, [{{:u, 8}, {224, 224, 3}, [:width, :height, :channels]}, {{:f, 32}, {}, []}]}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179461>} locking "{#Function<32.45485230/2 in EXLA.Backend.divide/3>, [{{:u, 8}, {224, 224, 3}}, {{:f, 32}, {}}], :cuda, [], []}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179489>} locking "{#Function<82.45485230/1 in EXLA.Backend.reshape/2>, [{{:f, 32}, {224, 224, 3}, [:width, :height, :channels]}]}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179496>} locking "{#Function<82.45485230/1 in EXLA.Backend.reshape/2>, [{{:f, 32}, {224, 224, 3}}], :cuda, [], []}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179530>} locking "{#Function<32.45485230/2 in EXLA.Backend.divide/3>, [{{:u, 8}, {224, 224, 3}, [:width, :height, :channels]}, {{:f, 32}, {}, []}]}"
{#PID<0.496.0>, #Reference<0.757356948.1021050881.179538>} locking "{#Function<32.45485230/2 in EXLA.Backend.divide/3>, [{{:u, 8}, {224, 224, 3}}, {{:f, 32}, {}}], :cuda, [], []}"
```

this appears to be because i'm loading 224x224 image pixels into a tensor and doing some preprocessing on them, like so:

```elixir
image_tensor = 
  pixels
  |> Nx.from_binary({:u, 8})
  |> Nx.reshape({meta[:width], meta[:height], meta[:channels]}, names: [:width, :height, :channels])
  |> Nx.divide(255.0)
```

...in a loop as a I crunch millions of images into feature vectors.

the weird part is, i looked over the logic in the LockedCache and it takes these keys and runs them through a map in a genserver to allow the first caller through, and to builds a list of other callers (etc. etc). so, this _shouldn't_ be happening, unless somehow these keys just "appear" to be the same when rendered with inspect(), but something about them isn't hashing out to the same value -- that'd _definitely_ cause misses in the LockedCache. i _suspect_ that might be happening because of the closure over `args` here, at the bottom of EXLA.Backend:

```elixir
  for {name, args, tensor_args} <- callbacks do
    args = Enum.map(args, &Macro.var(&1, __MODULE__))
    tensor_args = Enum.map(tensor_args, &Macro.var(&1, __MODULE__))

    @impl true
    def unquote(name)(unquote_splicing(args)) do
      expr_fn = fn unquote_splicing(tensor_args) ->
        Nx.Defn.Expr.unquote(name)(unquote_splicing(args))
      end

      EXLA.jit(expr_fn, [unquote_splicing(tensor_args)])
    end
  end
```

...and the variables being captured make a different instance of the closure on each call, and since _that_ is a component of the key... _maybe?_

**Comment by josevalim** [comment]
We are overriding the tensors as the closure args but I think something is leaking, most likely the `out` tensor.

**Comment by josevalim** [comment]
Ok, this is fixed on EXLA from the `main` branch. :)

**Comment by jallum** [comment]
yay! works wonderfully -- thanks for taking a look!

([for anyone that was as curious as i was...](https://github.com/elixir-nx/nx/commit/d2acc7673207be6076bf64270111f89c03979519))

a separate, but related question: the things that end up in LockedCache seem rather, erm, _permanently there_... if i have a very long running process that loads many, many different models over time, won't this become a problem?

**Comment by josevalim** [comment]
Right now it is permanent, yes! If/when that becomes a problem, we will be glad to consider options! :)
