### ISSUE TITLE
Add Axon.decompose/2 and Axon.compile/3

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/axon#303]
`Axon.decompose/2` breaks an Axon model into anonymous functions. This is useful to pass an Axon model around, such as in GANs. Its implementation is exactly what `Axon.compile/2` is today.

We should also introduce `Axon.compile/3`. `Axon.compile/3` will receive the model, the input, and the options, and it will call the upcoming `Nx.Defn.compile/3` to actually compile the Neural Network, so we don't have to rely on the JIT cache.

My only question is that `Axon.compile/3` would, for now, compile both `init` and `predict`, but `init` function would most likely go unused. However, compiling `init` should almost always be very fast, so perhaps it doesn't matter if we always compile it?

This also somewhat related to the `init` API requiring a tensor template for shape computation. This depends on upcoming `Nx.Defn.compile/3` API.

**Comment by josevalim** [comment]
We can also use Nx.Defn.Compile when we start training to avoid the cache altogether too.

**Comment by Benjamin-Philip** [comment]
Can I work on this?

**Comment by seanmor5** [comment]
Added in #310
