### ISSUE TITLE
Serialize/Deserialize Invalid Options Issues

### ISSUE THREAD

**Issue by fantypants** [elixir-nx/axon#314]
I've been running into some serialization issues with the model. It may be that I have loaded or saved the model wrong (just used File.write!/read! defaults), however, I thought id flag it here just in case.

**Updates Below**

```
params = 
    model
    |> Axon.Loop.trainer(loss_fn, optimizer)
    |> Axon.Loop.run(data, %{}, epochs: 5, iterations: 1)
    
serialized_model = Axon.serialize(model, params)
File.write!("./model_b", serialized_model)

serialized = File.read!("./model_b")
{saved_model, saved_params} = Axon.deserialize(serialized)
```
Results in the following:
```

** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: invalid option in list

    :erlang.binary_to_term(<<131, 104, 3, 97, 1, 116, 0, 0, 0, 12, 100, 0, 4, 97, 114, 103, 115, 108, 0, 0, 0, 1, 100, 0, 5, 108, 97, 121, 101, 114, 106, 100, 0, 4, 97, 120, 111, 110, 100, 0, 4, 97, 120, 111, 110, 100, 0, 5, 104, 111, ...>>, [:safe])
    (axon 0.1.0) lib/axon.ex:3471: Axon.deserialize/2
```

If i use binary to term on the raw file:
```
{_, m, p} = :erlang.binary_to_term(serialized)

{1,
 %{args: [:layer], axon: :axon ..},
 [
   <<131, 104, 3, 97, 1, 100, 0, 6, 108, 105, 116, 116, 108, 101, 104, 2, 100,
     0, 9, 99, 111, 110, 116, 97, 105, 110, 101, 114, 116, 0, 0, 0, 3, 109, 0,
     0, 0, 7, 100, 101, 110, 115, 101, 95, 48, 104, ...>>,
     ...
 ]}

```

**Update 1**:

This is only happening if you save the Axon.serialize using File.write! in another process, once you run a new process and load the relevant file output you get the below. 

If you save the serialized state and load it straight away (from the same process, or mix run -e) there isn't any issue.

**Update 2**:
After inspecting deserialize/2 in Axon, it seems its it's throwing this error from the map_to_axon call, as well as an error from Nx.deserialize.
```

%Inspect.Error{
  message: "got BadFunctionError with message \"function #Function<58.92691295/2 in Axon> is invalid, likely because it points to an old version of the code\" while inspecting %{__struct__: Axon, args: [:layer], hooks: [], id: 20, name: #Function<57.92691295/2 in Axon>, op: :softmax, op_name: :softmax, opts: [], output_shape: {nil, 1, 9}, parameters: [], parent: [%{__struct__: Axon, args: [:layer, :parameter, :parameter], hooks: [], id: 19, name: #Function<57.92691295/2 in Axon>, op: :dense, op_name: :dense, opts: [], output_shape: {nil, 1, 9}, parameters: [%Axon.Parameter{frozen: false, id: 17, initializer: :glorot_uniform, name: \"kernel\", shape: {100, 9}}, %Axon.Parameter{frozen: false, id: 18, initializer: :zeros, name: \"bias\", shape: {9}}], parent: [%{__struct__: Axon, args: [:layer], hooks: [], id: 16, name: #Function<57.92691295/2 in Axon>, op: :dropout, op_name: :dropout, opts: [rate: 0.2], output_shape: {nil, 1, 100}, parameters: [], parent: [%{__struct__: Axon, args: [:layer], hooks: [], id: 15, name: #Function<38.92691295/2 in Axon>, op: #Function<41.92691295/2 in Axon>, op_name: :elem, opts: [], output_shape: {nil, 1, 100}, parameters: [], parent: [%{__struct__: Axon, args: [...], ...}], policy: p=f32 c=f32 o=f32}], policy: p=f32 c=f32 o=f32}], policy: p=f32 c=f32 o=f32}], policy: p=f32 c=f32 o=f32}"
}
```

**Update 3**:
Error calling Nx.deserialize function from Axon.deserialize, isolating this call produces the error in question:

```** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: invalid option in list
```

**Comment by josevalim** [comment]
@seanmor5 I don't think you want to use the `:safe` option because it requires all atoms in the payload to have already been loaded in memory. So If you have an atom defined in Axon.Foo.Bar.Baz, that module has to have been loaded.

@fantypants can you please send a PR that removes the `:safe` argument?

**Comment by fantypants** [comment]
> @seanmor5 I don't think you want to use the `:safe` option because it requires all atoms in the payload to have already been loaded in memory. So If you have an atom defined in Axon.Foo.Bar.Baz, that module has to have been loaded.
> 
> @fantypants can you please send a PR that removes the `:safe` argument?

Sure can, i'll test it now.

**Comment by fantypants** [comment]
Closing this issue as it requires a seperate issue, the Nx.deserialize/2 issue should be fixed with the open PR. Opening seperate issue for map_to_axon/1 issue
