### ISSUE TITLE
The resize layer produces invalid output

### ISSUE THREAD

**Issue by jonatanklosko** [elixir-nx/axon#320]
I believe methods other than `:nearest` don't currently work.

<details>
<summary>nearest</summary>

![image](https://user-images.githubusercontent.com/17034772/179411435-25016e35-1f9e-4724-8720-1d17bf328fe2.png)

</details>

<details>
<summary>linear</summary>

![image](https://user-images.githubusercontent.com/17034772/179411470-029e86d5-8337-44d2-9f83-1fb299ca0fa4.png)

</details>

<details>
<summary>cubic</summary>

![image](https://user-images.githubusercontent.com/17034772/179411479-8ecc793e-dc97-4b97-84f9-e26d2ae52127.png)

</details>

Also related to https://github.com/elixir-nx/nx/issues/838.

---

We can port the implementation from the other project. We could use `NxImage` once we extract it, however as far as I understand Axon wants to support arbitrary number of spatial dimensions, so we will need a tweaked implementation.

**Comment by jnnks** [comment]
(off topic) Are you able to give more info about `NxImage`? I am in the middle of exploring image processing in Elixir on the edge and that sounds very interesting. I suppose it's an internal project, as there are exaclty two hits on google for "NxImage" :D

**Comment by jnnks** [comment]
@jonatanklosko crop and resize is a good start. I'd be interested to contribute to further implementation when the time comes.
