### ISSUE TITLE
Switch recurrent outputs to match Elixir convention

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#335]
Recurrent functions currently return `{state, seq}`. The `state` is like an accumulator and `seq` is like an Enumerable. Elixir's map_reduce returns `{enum, acc}`, so I think it makes sense to use that convention here

**Comment by fantypants** [comment]
Is this for documentation sake? if so, absolutely yes! if the aim is to provide a transparent API for new-to-ai developers alike; this is a fantastic step in the right direction. As someone who has recently done that journey, the semantics of the language was the most important thing for me to be able to work things out.
