### ISSUE TITLE
Add Axon serving/deployment API

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#369]

**Comment by seanmor5** [comment]
`Nx.Serving` provides a good enough serving foundation that I don't think this is necessary, maybe it will be explored in the future

**Comment by thiagopromano** [comment]
Hey @seanmor5 , I am currently trying to set up an `Nx.Serving` to run the Axon models. The only documentation I found was either your Dockyard post about the `Axon.serving` that wasn't merged on https://github.com/elixir-nx/axon/pull/377. Do you have any documentation or sample code on how to set up a process that serves an Axon model?
