### ISSUE TITLE
Evaluator not behaving as expected

### ISSUE THREAD

**Issue by Vagab** [elixir-nx/axon#383]
Hi everyone,

I tried to follow this official [example](https://fly.io/phoenix-files/recognize-digits-using-ml-in-elixir/) from the repo, put up everything in a livebook like this:

### Setup
```elixir
Mix.install([
  {:nx, "~> 0.3"},
  {:scidata, "~> 0.1.5"},
  {:axon, "~> 0.2.0"},
  {:exla, "~> 0.3.0"},
  {:explorer, "~> 0.3.0"}
])
```

### Module
```elixir
defmodule Model do
  def new({channels, height, weight}) do
    Axon.input("stuff", shape: {channels, height, weight})
    |> Axon.flatten()
    |> Axon.dense(128, activation: :relu)
    |> Axon.dense(10, activation: :softmax)
  end

  def train(model, training_data, validation_data) do
    model
    |> Axon.Loop.trainer(:categorical_cross_entropy, Axon.Optimizers.adam(0.01))
    |> Axon.Loop.metric(:accuracy, "accuracy")
    |> Axon.Loop.validate(model, validation_data)
    |> Axon.Loop.run(training_data, %{}, epochs: 1, compiler: EXLA)
  end

  def test(model, test_data) do
    model
    |> Axon.Loop.evaluator()
    |> Axon.Loop.metric(:accuracy, "accuracy")
    |> Axon.Loop.run(test_data)
  end

  def download do
    Scidata.MNIST.download()
  end

  def transform_labels({binary, type, _}) do
    binary
    |> Nx.from_binary(type)
    |> Nx.new_axis(-1)
    |> Nx.equal(Nx.tensor(Enum.to_list(0..9)))
  end

  def transform_images({binary, type, shape}) do
    binary
    |> Nx.from_binary(type)
    |> Nx.reshape(shape)
    |> Nx.divide(255)
  end
end
```

### The script
```elixir
batch_size = 32

{images, labels} = Model.download()

labels = 
  labels
  |> Model.transform_labels()
  |> Nx.to_batched(batch_size)

images = 
  images
  |> Model.transform_images()
  |> Nx.to_batched(batch_size)

data = Enum.zip(images, labels)

training_count = floor(0.8 * Enum.count(data))
validating_count = floor(0.2 * training_count)

{training_data, testing_data} = Enum.split(data, training_count)
{validating_data, training_data} = Enum.split(training_data, validating_count)

model = Model.new({1, 28, 28})

IO.puts("Training...")

model = Model.train(model, training_data, validating_data)

IO.puts("Testing...")

Model.test(model, testing_data)
```

But it fails at the `Model.test` part with:
> ** (ArgumentError) Invalid model %{"dense_0" => %{"bias" ...
> \>}}, a valid model is an Axon struct or a tuple of {init_fn, forward_fn} with signatures init_fn() :: model_state, forward_fn(model_state, inp) :: prediction

A little bit more context:
The guide is seemed to have been written for `Axon -v 0.1`, which requires a state of a model to be passed as well as a model. I have instead used `Axon -v 0.2`(to be fair I have also failed to replicate that exact example with `-v 0.1`) and tried passing either the state of a model or an actual model to the evaluator but neither worked. This is probably also the case with the credit-cards example, since there the `evaluator/2` is also used. 

Which I imagine is not what's supposed to happen. Anyway, is there a way to fix this or if this is an expected thing, is there a way to hack around it?

**Comment by seanmor5** [comment]
Hey @Vagab, I believe your actual issue is that `Model.train/3` does not return the trained model, but rather the trained model state. In Axon, you always need to carry the model struct AND the model parameters. I believe your `test/2` function also needs to be updated to:

```elixir
  def test(model, model_state, test_data) do
    model
    |> Axon.Loop.evaluator()
    |> Axon.Loop.metric(:accuracy, "accuracy")
    |> Axon.Loop.run(test_data, model_state)
  end
```

And then you can update the script:

```elixir
model_state = Model.train(model, training_data, validating_data)

IO.puts("Testing...")

Model.test(model, model_state, testing_data)
```

**Comment by Vagab** [comment]
thanks @seanmor5, this solved the issue :) Would be cool if such examples were available on the main repo. I could add something to the wiki, or at least we should link an up-to-date livebook. I can write one. What do you think?

**Comment by seanmor5** [comment]
I would gladly accept example contributions!
