### ISSUE TITLE
[QUESTION] Switch off `Axon.Loop.run` metric stdout

### ISSUE THREAD

**Issue by Benjamin-Philip** [elixir-nx/axon#396]
When I am in testing or in production, I may not want the metrics used during developed printed. Metrics such as:

```
Epoch: 0, Batch: 1850, Accuracy: 0.8927606 loss: 0.3565226
Epoch: 1, Batch: 1850, Accuracy: 0.9309664 loss: 0.2938470
Epoch: 2, Batch: 1850, Accuracy: 0.9429026 loss: 0.2605216
Epoch: 3, Batch: 1850, Accuracy: 0.9509048 loss: 0.2371558
Epoch: 4, Batch: 1850, Accuracy: 0.9524919 loss: 0.2207826
```

Or

```
Batch: 1874, Accuracy: 0.9613333
```

that is printed during training or testing on calling `Axon.Loop.run`.

Is there some way to switch this off in the `dev` and `prod` environments, preferably in my `config.exs`?

**Comment by josevalim** [comment]
I believe you can turn it on and off using the loop API. then if necessary, you can add the relevant config, read it yourself, and pass as argument to the loop API.

**Comment by josevalim** [comment]
Oops, to be clear, I am assuming there is an Axon.Loop API but @seanmor5 would be the best person to tell. My point is just that reading from config should be your responsibility, not Axon’s. :)

**Comment by Benjamin-Philip** [comment]
> reading from config should be your responsibility, not Axon’s. :)

That's fine, but I see no way of turning it off in the docs for [`run/4`](https://hexdocs.pm/axon/Axon.Loop.html#run/4).

**Comment by seanmor5** [comment]
It's not well documented, but when you declare `trainer` you can specify `log: -1` (or any negative number) and it will turn off logging. If you want to open a PR expanding the docs, that would be great!

**Comment by Benjamin-Philip** [comment]
> when you declare trainer you can specify log: -1 (or 0 or any negative number) 

Looking through the src, the same is not true for `Loop.evaluator/1`. Should I send a PR for this as well?

**Comment by seanmor5** [comment]
Definitely!
