### ISSUE TITLE
Make building networks deterministic

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/axon#410]
Currently, assembling and Axon.building the same network twice leads to different models, which means they cannot share the jit cache. Here is a compiler_test:

```
  describe "determinism" do
    test "builds the same model multiple times" do
      builder = fn -> Axon.input("input", shape: {nil, 784}) |> Axon.dense(128) end
      {_, predict_fn1} = Axon.Compiler.build(builder.(), [])
      {_, predict_fn2} = Axon.Compiler.build(builder.(), [])
      assert predict_fn1 == new_predict_fn2
    end
  end
```

I am assuming we don't care about determinism in `init_fn`. If we do, its only additional source of non-determinism is the `:erlang.system_time()` call.

For the `predict_fn`, the source of determinism are:

1. System.unique_integer in parameter names
2. System.unique_integer in input names
3. `|> Nx.backend_copy(Nx.Defn.Expr)`

Step 3 is easy to address: Instead, we can do a `backend_copy` to the binary backend and keep a reference to the binary (after all, that's what Nx.Defn.Expr will do anyway). This is fine as long as we use the reference only once (which seems to always be the case).

For the first two, I am not sure. Let me know if I can help somehow @seanmor5.

**Comment by seanmor5** [comment]
Resolved in #427
