### ISSUE TITLE
Is it possible to remove the last layers from a neural network?

### ISSUE THREAD

**Issue by lucaong** [elixir-nx/axon#446]
In order to use an image classifier model for image embedding, one strategy is to use the output of a hidden layer as the embedding. One can therefore remove the last few layers of a trained classifier model such as ResNet. I could not find a function to remove layers in `Axon` though. Is there is a way to do that?

**Comment by seanmor5** [comment]
You can pop layers out of the model with `Axon.pop_node/1`:

```elixir
model = Axon.input("foo") |> Axon.dense(32) |> Axon.dense(1)
IO.inspect model
```
```
#Axon<
  inputs: %{"foo" => nil}
  outputs: "dense_1"
  nodes: 3
>
```

```elixir
{_node, updated_model} = Axon.pop_node(model)
IO.inspect updated_model
```

```
 #Axon<
   inputs: %{"foo" => nil}
   outputs: "dense_0"
   nodes: 2
 >
```

**Comment by lucaong** [comment]
Thanks a lot! Sorry I missed it in the docs
