### ISSUE TITLE
Different sentence embeddings for same input when using Axon.predict/3

### ISSUE THREAD

**Issue by jannikbecher** [elixir-nx/axon#488]
While exploring sentence embeddings I stumbled upon this weird behavior.
The vector embeddings differ when using the Axon.predict function with multiple inputs, while it is the same when running with the same input twice.

Here is a livebook to reproduce it:

# Test Axon.predict behavior

```elixir
Mix.install(
  [
    {:kino_bumblebee, "~> 0.2.1"},
    {:exla, "~> 0.5.1"}
  ],
  config: [nx: [default_backend: EXLA.Backend]]
)
```

## Section

```elixir
model_name = "sentence-transformers/all-MiniLM-L6-v2"
{:ok, model_info} = Bumblebee.load_model({:hf, model_name})
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, model_name})
```

```elixir
input = """
fwrevjrek;vjeakvl;jreavkl;ajva
rvjreaklv;jeakrv;jeavkrea;ljvreka;vrea
veavjkea;lvjrkea;lvjreka;lvjrsava
vjk;jrvk;leajvke;lav
davreavreav
reear
rea
bbesrgre
ararresabe
"""

multiple_inputs = Bumblebee.apply_tokenizer(tokenizer, [input, input], length: 100)
single_input1 = Bumblebee.apply_tokenizer(tokenizer, [input], length: 100)
single_input2 = Bumblebee.apply_tokenizer(tokenizer, [input], length: 100)
```

## Multiple Inputs

```elixir
res1 =
  Axon.predict(model_info.model, model_info.params, multiple_inputs).pooled_state[0]
  |> Nx.to_list()
  |> Enum.sum()

res2 =
  Axon.predict(model_info.model, model_info.params, multiple_inputs).pooled_state[1]
  |> Nx.to_list()
  |> Enum.sum()

res1 == res2
```

## Single Input

```elixir
res1 =
  Axon.predict(model_info.model, model_info.params, single_input1).pooled_state[0]
  |> Nx.to_list()
  |> Enum.sum()

res2 =
  Axon.predict(model_info.model, model_info.params, single_input2).pooled_state[0]
  |> Nx.to_list()
  |> Enum.sum()

res1 == res2
```

**Comment by seanmor5** [comment]
This would be something with the Bumblebee implementation. I can't confirm whether or not our implementation is correct. cc @jonatanklosko

**Comment by jonatanklosko** [comment]
Hey @jannikbecher. For me both equalities pass actually, what differs are the results between single and multi runs (comparing `res1`/`res2` across sections), but the differences seems to be within numerical precision error.

Other than that, when running with `Torchx.Backend` all results are exactly the same, so I think it's likely that XLA does something slightly different underneath in each case (since it optimises computation based on the input shape) and that makes the results not *exactly* the same, but correct :)

**Comment by jonatanklosko** [comment]
@jannikbecher so unless the tensors in your case differ notably, I think we are good!

**Comment by jannikbecher** [comment]
@jonatanklosko ahhh I see. Thank you for looking into it! :)
