### ISSUE TITLE
Passing f32 data into LSTM with Axon.Loop trainer+run causes while shape mismatch error

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/axon#490]
```elixir
input = Axon.input("input_series", shape: put_elem(Nx.shape(time_x), 0, nil))

model =
  input
  |> Axon.lstm(128, activation: :relu)
  |> elem(0)
  |> Axon.dropout(rate: 0.25)
  |> Axon.lstm(64, activation: :relu)
  |> elem(0)
  |> Axon.dropout(rate: 0.25)
  |> Axon.lstm(32, activation: :relu)
  |> elem(0)
  |> Axon.dropout(rate: 0.25)
  |> Axon.dense(1)

model
|> Axon.Loop.trainer(:mean_squared_error, Axon.Optimizers.adam())
|> Axon.Loop.run(Stream.zip(Nx.to_batched(time_x, 50), Nx.to_batched(Nx.new_axis(time_y, 2), 50)))
```

**Comment by seanmor5** [comment]
Btw, looking at this, it's not advisable to use dropout after an LSTM layer. See https://arxiv.org/pdf/1512.05287.pdf

This is still a bug though

**Comment by polvalente** [comment]
I was just copying a Kaggle solution to practice RNNs :)

Thanks for the advice!

**Comment by polvalente** [comment]
@seanmor5 did you fix this bug at the time?

@krstopro the problem I ran into was related to some of the inner random key states being upcast from u32 to f32

**Comment by danieljaouen** [comment]
I am also seeing an issue which I think has to do with my model changing to `:f32` (but from `:f64` in my case).  See: https://elixirforum.com/t/getting-batches-to-work-with-axon/57482/3

**Comment by dc0d** [comment]
Facing the same issue.

**Comment by seanmor5** [comment]
This issue should be fixed with the new `Axon.ModelState` changes - dropout keys and other model state are no longer considered part of the training parameters and so shouldn't accidentally get cast anywhere
