### ISSUE TITLE
How to verify mixed precision is working for language models

### ISSUE THREAD

**Issue by toranb** [elixir-nx/axon#496]
Originally I was [reading](https://lightning.ai/pages/community/tutorial/accelerating-large-language-models-with-mixed-precision-techniques/) about how people do this type of mixed precision work in python today and found it was a configuration like you see here
    
<img width="897" alt="Screenshot 2023-05-26 at 10 19 28 AM" src="https://github.com/elixir-nx/axon/assets/147411/e7593ba3-3c81-43e4-b9df-22b5f0367c8e">

Wanting to accomplish this in Axon I started by looking at [this pull request ](https://github.com/elixir-nx/axon/pull/74/files)about mixed precision to use a `bf: 16` policy when fine tuning BERT but it doesn't appear to be working and I'm looking for clues to prove/disprove it.

I noticed in the [training test code](https://github.com/elixir-nx/axon/blob/b7b19c61ca0f242a8be4f02d87f0657146609f29/test/mixed_precision_test.exs#L62) for `correctly maintains parameter type after train step` the assertions verify the params after training so I went ahead and did the same. But in my example it shows I'm still using `f: 32` for some odd reason.

```
%{
  "bias" => #Nx.Tensor<
    f32[768]
    EXLA.Backend<cuda:0, 0.198458620.3614310435.139911>
    [1.1483082926133648e-4, 1.5510240336880088e-4, 8.907304618333001e-7, 4.598435771185905e-5, 7.280074351001531e-5, 3.678119392134249e-4, -1.5480619913432747e-4, -6.495109118986875e-5,-0.015686072409152985, ...]
  >,
  "kernel" => #Nx.Tensor<
    f32[768][768]
    EXLA.Backend<cuda:0, 0.198458620.3614310435.139912>
    [
      [0.09109397977590561, -0.018297171220183372, 0.01780594326555729, 0.03939569741487503, 0.12485719472169876, 7.235617376863956e-4, 0.01607041247189045, 0.07742417603731155, ...],
      ...
    ]
  >
}
```

I also found no reduction in memory at runtime (using the configuration that avoids using all GPU VRAM until it's truly needed) which makes me suspicious that this policy is truly applied. I assume it has more to do with the model and my fine tuning than the mixed precision code implemented in that PR so here is my approach.

Here is the full source for my fine tuning example with this mixed precision policy applied

```elixir
    ## fine tune bert
    %{model: model, params: params} = model

    [{input, _}] = Enum.take(train_data, 1)
    Axon.get_output_shape(model, input)

    logits_model = Axon.nx(model, & &1.logits)

    loss =
      &Axon.Losses.categorical_cross_entropy(&1, &2,
        reduction: :mean,
        from_logits: true,
        sparse: true
      )

    optimizer = Axon.Optimizers.adam(2.0e-5)
    accuracy = &Axon.Metrics.accuracy(&1, &2, from_logits: true, sparse: true)

    policy = Axon.MixedPrecision.create_policy(
      params: {:bf, 16},
      compute: {:bf, 16},
      output: {:bf, 16}
    )

    trained_model_state =
      logits_model
      |> Axon.MixedPrecision.apply_policy(policy, except: [:batch_norm])
      |> Axon.Loop.trainer(loss, optimizer, log: 1)
      |> Axon.Loop.metric(accuracy, "accuracy")
      |> Axon.Loop.run(train_data, params, epochs: 1, compiler: EXLA, strict?: false)

    # this is how I pulled the params to see if they are f32/bf16
    trained_model_state
    |> Map.keys()
    |> Enum.take(1)
    |> Enum.each(fn st ->
      trained_model_state[st] |> IO.inspect(label: "compare this...")
    end)
```

**Comment by seanmor5** [comment]
First, the precision in that pytorch screenshot is not really the same as in the Axon mixed precision module. The closest equivalent in Nx is setting the EXLA precision to `:lowest` by configuring the compiler options.

Second, I think the issue is that with pretrained models passed to `train` we are not downcasting the parameters. I will fix

**Comment by toranb** [comment]
thanks for jumping into this @seanmor5 !! 

About the compiler option for `lowest` -is that something you have used to go further/on less hardware? Does that setting drop from f32 to f16 or something else? I'm happy to source dive -what is the best spot to learn more about that specific compiler option?

**Comment by seanmor5** [comment]
Here's some documentation on it: https://jax.readthedocs.io/en/latest/jax.lax.html#jax.lax.Precision
