### ISSUE TITLE
kino_vega_lite_plot: step number is wrong when plotting multiple metrics during a same loop

### ISSUE THREAD

**Issue by robinmonjo** [elixir-nx/axon#523]
If we plot more than one metric during a training loop, the `absolute_iteration` will be called for each plots and be incremented every time. So if we plot 2 metrics we have:

```
- iteration 1
       plot_1: absolute_iteration = 1
       plot_2: absolute_iteration = 2 # this is wrong
- iteration 2
       plot_1: absolute_iteration = 3 # this is wrong
       plot_2: absolute_iteration = 4 # this is wrong
...
```

The solution would be to store one absolute_iteration metadata per metric, can take care of this later if solutions is ok.

**Comment by seanmor5** [comment]
I think you're right! If you want to take a stab at it let me know :)
