### ISSUE TITLE
Online deep learning in Axon

### ISSUE THREAD

**Issue by sutgeorge** [elixir-nx/axon#533]
This is not really an issue, rather it is a potential idea that could be implemented in Axon (if it is not already implemented).

My question is: Does Axon have support for online deep learning yet? Here is the paper that explains in detail what online learning is used for (you can read the abstract if you'd like, to get an understanding of what it can be used for): https://arxiv.org/abs/1711.03705

There is already an online deep learning library in Python called RiverML which we could take as an inspiration.

I would like contributing to the project in this direction if there is a need for such a feature. Thanks!

**Comment by seanmor5** [comment]
Hey @sutgeorge thanks for bring this up! This is not currently supported in Axon, but the idea is interesting and I would encourage you to try it out! I don't think an implementation would necessarily live within Axon, but rather as a separate library built on top of Axon. Then, if there are specific components that would be generally useful we can add them here. Does that make sense?

I am happy to help answer any questions you have in building this out, feel free to drop in the EEF Slack in the #machine-learning channel and we can help. i think this would be a cool addition to the ecosystem!

**Comment by sutgeorge** [comment]
Thanks for the response! Yes, it is pretty much one of the missing elements in the elixir-nx project. I'll think about it.
