### ISSUE TITLE
Tagged versions missing in the repo compared to the ones in hexdocs.pm

### ISSUE THREAD

**Issue by NJichev** [elixir-nx/axon#585]
When browsing the latest docs for 0.6.1 it doesn't open the code for the tagged version via the "Show code" widget on the right of functions. It would be a nice to have it in the github repo in order to browse the code. For now I'll just default to 0.6.0 since the tagged branch exists correctly.

Here's a screenshot after pressing the widget inside hexdocs.pm
<img width="1251" alt="Screenshot 2024-07-10 at 16 06 12" src="https://github.com/elixir-nx/axon/assets/6959211/a7a6447b-22ca-4356-9daa-ae5d3ecfacee">

Edit: I realised that this could be an artifact of just building the docs for the latest version in main as 0.6.1 before publishing the real 0.6.1 version, if so I'll just close this issue.

**Comment by seanmor5** [comment]
Sorry about that, I just went back through and tagged+released 0.6 and 0.6.1 in GitHub
