### ISSUE TITLE
`Axon.Display.as_graph` breaks when updating axon from 0.5 to 0.6

### ISSUE THREAD

**Issue by nickgnd** [elixir-nx/axon#594]
Hey there 👋 
First of all, thanks again for all the work and effort you all are putting into the Nx libraries, i'm truly amazed by your results.

Then, I was updating the Nx dependencies in a Livebook of mine and I spotted an issue when using `Axon.Display.as_graph`.

Here the snippet to reproduce it:

```elixir
Mix.install(
  [
    {:nx, "~> 0.6.1", override: true},
    {:axon, "~> 0.6"},
    {:exla, "~> 0.6.0"},
    {:kino, "~> 0.14"}
  ],
  config: [nx: [default_backend: EXLA.Backend]]
)

batch_size = 4
block_size = 8
shape = {batch_size, block_size}

bigram_model =
  Axon.input("sequence", shape: shape)
  |> Axon.embedding(65, 65)

Axon.Display.as_graph(bigram_model, Nx.template(shape, :f32),
  direction: :top_down
)
```

It fails with the following error:

```
** (Axon.CompileError) exception found when compiling layer Axon.Layers.embedding/3 named embedding_0:

    ** (ArgumentError) indices must be an integer tensor, got {:f, 32}
        (nx 0.6.4) lib/nx.ex:14150: Nx.take/3
    

(pass debug: true to build/compile see where the layer was defined)


Compiling of the model was initiated at:

    (axon 0.6.1) lib/axon.ex:3406: anonymous fn/3 in Axon.get_output_shape/3
    (nx 0.6.4) lib/nx/defn/compiler.ex:158: Nx.Defn.Compiler.runtime_fun/3
    (axon 0.6.1) lib/axon/defn.ex:14: Axon.Defn.__jit__/5
    (nx 0.6.4) lib/nx/defn.ex:443: Nx.Defn.do_jit_apply/3
    (axon 0.6.1) lib/axon.ex:3409: Axon.get_output_shape/3
    #cell:5i2jifureixx5mee:11: (file)
```

I tried to debug it further, but I couldn't discover much.

I think the `Nx.take/3` that is raising the exception is probably called [here](https://github.com/elixir-nx/axon/blob/2a2d165b1e65b2c9892fedf09b53f1f90c45788f/lib/axon/layers.ex#L1798) in `Axon.Layers.embedding/3`, which it is maybe called [here](https://github.com/elixir-nx/axon/blob/2a2d165b1e65b2c9892fedf09b53f1f90c45788f/lib/axon.ex#L3076) in `Axon.embedding/4`.... 🤔 

☝️ the same snippet used to work correctly with Axon v0.5.1 (see screenshot)

```elixir
Mix.install(
  [
    {:nx, "~> 0.6.1", override: true},
    {:axon, "~> 0.5.1"},
    {:exla, "~> 0.6.0"},
    {:kino, "~> 0.14"}
  ],
  config: [nx: [default_backend: EXLA.Backend]]
)
```

<img width="944" alt="image" src="https://github.com/user-attachments/assets/99dba788-f8af-4bfb-858d-2996c34f74fd">

Let me know if I can help in any way, cheers ✌️

**Comment by seanmor5** [comment]
Can you try from the main branch?

**Comment by nickgnd** [comment]
Hey @seanmor5 
I just tried, but no luck. I got the same error

```elixir
Mix.install(
  [
    {:nx, "~> 0.6.1", override: true},
    {:axon, git: "git@github.com:elixir-nx/axon.git", ref: "main"},
    {:exla, "~> 0.6.0"},
    {:kino, "~> 0.14"}
  ],
  config: [nx: [default_backend: EXLA.Backend]]
)

# ....
```

Error:

```
** (Axon.CompileError) exception found when compiling layer Axon.Layers.embedding/3 named embedding_0:

    ** (ArgumentError) indices must be an integer tensor, got {:f, 32}
        (nx 0.6.4) lib/nx.ex:14150: Nx.take/3
    

(pass debug: true to build/compile to see where the layer was defined)


Compiling of the model was initiated at:

    (axon 0.6.1) lib/axon.ex:3650: anonymous fn/3 in Axon.get_output_shape/3
    (nx 0.6.4) lib/nx/defn/compiler.ex:158: Nx.Defn.Compiler.runtime_fun/3
    (axon 0.6.1) lib/axon/defn.ex:14: Axon.Defn.__jit__/5
    (nx 0.6.4) lib/nx/defn.ex:443: Nx.Defn.do_jit_apply/3
    (axon 0.6.1) lib/axon.ex:3655: Axon.get_output_shape/3
    #cell:gef2wlvqmz5hlji6:10: (file)
```

**Comment by seanmor5** [comment]
@nickgnd I just looked again, and I think the issue is that you are passing an `:f32` template tensor as input. When using the embedding layer, the inputs need to be an integer type. If you change `Nx.template(shape, :f32)` to `Nx.template(shape, :u32)` can you let me know if it works?

**Comment by nickgnd** [comment]
@seanmor5 you're totally right and it makes a lot of sense! It works indeed 🎉 

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/d4ed953f-777a-4c5c-9137-e7f9bb1ff81c">

And sorry, I should pay more attention to error message 🙈
