### ISSUE TITLE
Axon.Training.train gives an error

### ISSUE THREAD

**Issue by anandgeorge** [elixir-nx/axon#62]
Having a small issue. I try to run Axon.Training.train and it gives an error

function Nx.dot/4 is undefined or private. Did you mean one of:

      * dot/2
      * dot/6

Could you please help.

Thanks

**Comment by josevalim** [comment]
I have added Nx.dot/4 back and updated Axon. Please update your Axon and you should be good, thanks!

**Comment by anandgeorge** [comment]
Thank you. That was really quick
